// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetDataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataRequest) Reset()         { *m = GetDataRequest{} }
func (m *GetDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataRequest) ProtoMessage()    {}
func (*GetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_e535c14c20fe8460, []int{0}
}
func (m *GetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataRequest.Unmarshal(m, b)
}
func (m *GetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataRequest.Marshal(b, m, deterministic)
}
func (dst *GetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataRequest.Merge(dst, src)
}
func (m *GetDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataRequest.Size(m)
}
func (m *GetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataRequest proto.InternalMessageInfo

func (m *GetDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetDataResponse struct {
	Value                string   `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataResponse) Reset()         { *m = GetDataResponse{} }
func (m *GetDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataResponse) ProtoMessage()    {}
func (*GetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_e535c14c20fe8460, []int{1}
}
func (m *GetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataResponse.Unmarshal(m, b)
}
func (m *GetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataResponse.Marshal(b, m, deterministic)
}
func (dst *GetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataResponse.Merge(dst, src)
}
func (m *GetDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataResponse.Size(m)
}
func (m *GetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataResponse proto.InternalMessageInfo

func (m *GetDataResponse) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetDataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDataRequest) Reset()         { *m = SetDataRequest{} }
func (m *SetDataRequest) String() string { return proto.CompactTextString(m) }
func (*SetDataRequest) ProtoMessage()    {}
func (*SetDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_e535c14c20fe8460, []int{2}
}
func (m *SetDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataRequest.Unmarshal(m, b)
}
func (m *SetDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataRequest.Marshal(b, m, deterministic)
}
func (dst *SetDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataRequest.Merge(dst, src)
}
func (m *SetDataRequest) XXX_Size() int {
	return xxx_messageInfo_SetDataRequest.Size(m)
}
func (m *SetDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataRequest proto.InternalMessageInfo

func (m *SetDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetDataRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetDataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDataResponse) Reset()         { *m = SetDataResponse{} }
func (m *SetDataResponse) String() string { return proto.CompactTextString(m) }
func (*SetDataResponse) ProtoMessage()    {}
func (*SetDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_e535c14c20fe8460, []int{3}
}
func (m *SetDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDataResponse.Unmarshal(m, b)
}
func (m *SetDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDataResponse.Marshal(b, m, deterministic)
}
func (dst *SetDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDataResponse.Merge(dst, src)
}
func (m *SetDataResponse) XXX_Size() int {
	return xxx_messageInfo_SetDataResponse.Size(m)
}
func (m *SetDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDataResponse proto.InternalMessageInfo

type Pair struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pair) Reset()         { *m = Pair{} }
func (m *Pair) String() string { return proto.CompactTextString(m) }
func (*Pair) ProtoMessage()    {}
func (*Pair) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_e535c14c20fe8460, []int{4}
}
func (m *Pair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pair.Unmarshal(m, b)
}
func (m *Pair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pair.Marshal(b, m, deterministic)
}
func (dst *Pair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pair.Merge(dst, src)
}
func (m *Pair) XXX_Size() int {
	return xxx_messageInfo_Pair.Size(m)
}
func (m *Pair) XXX_DiscardUnknown() {
	xxx_messageInfo_Pair.DiscardUnknown(m)
}

var xxx_messageInfo_Pair proto.InternalMessageInfo

func (m *Pair) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Pair) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type GetAllDataRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllDataRequest) Reset()         { *m = GetAllDataRequest{} }
func (m *GetAllDataRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllDataRequest) ProtoMessage()    {}
func (*GetAllDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_e535c14c20fe8460, []int{5}
}
func (m *GetAllDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllDataRequest.Unmarshal(m, b)
}
func (m *GetAllDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllDataRequest.Marshal(b, m, deterministic)
}
func (dst *GetAllDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllDataRequest.Merge(dst, src)
}
func (m *GetAllDataRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllDataRequest.Size(m)
}
func (m *GetAllDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllDataRequest proto.InternalMessageInfo

type GetAllDataResponse struct {
	Result               []*Pair  `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllDataResponse) Reset()         { *m = GetAllDataResponse{} }
func (m *GetAllDataResponse) String() string { return proto.CompactTextString(m) }
func (*GetAllDataResponse) ProtoMessage()    {}
func (*GetAllDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_e535c14c20fe8460, []int{6}
}
func (m *GetAllDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllDataResponse.Unmarshal(m, b)
}
func (m *GetAllDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllDataResponse.Marshal(b, m, deterministic)
}
func (dst *GetAllDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllDataResponse.Merge(dst, src)
}
func (m *GetAllDataResponse) XXX_Size() int {
	return xxx_messageInfo_GetAllDataResponse.Size(m)
}
func (m *GetAllDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllDataResponse proto.InternalMessageInfo

func (m *GetAllDataResponse) GetResult() []*Pair {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteDataRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDataRequest) Reset()         { *m = DeleteDataRequest{} }
func (m *DeleteDataRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDataRequest) ProtoMessage()    {}
func (*DeleteDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_e535c14c20fe8460, []int{7}
}
func (m *DeleteDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDataRequest.Unmarshal(m, b)
}
func (m *DeleteDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDataRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDataRequest.Merge(dst, src)
}
func (m *DeleteDataRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDataRequest.Size(m)
}
func (m *DeleteDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDataRequest proto.InternalMessageInfo

func (m *DeleteDataRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type DeleteDataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDataResponse) Reset()         { *m = DeleteDataResponse{} }
func (m *DeleteDataResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDataResponse) ProtoMessage()    {}
func (*DeleteDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_e535c14c20fe8460, []int{8}
}
func (m *DeleteDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDataResponse.Unmarshal(m, b)
}
func (m *DeleteDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDataResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDataResponse.Merge(dst, src)
}
func (m *DeleteDataResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDataResponse.Size(m)
}
func (m *DeleteDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDataResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetDataRequest)(nil), "proto.GetDataRequest")
	proto.RegisterType((*GetDataResponse)(nil), "proto.GetDataResponse")
	proto.RegisterType((*SetDataRequest)(nil), "proto.SetDataRequest")
	proto.RegisterType((*SetDataResponse)(nil), "proto.SetDataResponse")
	proto.RegisterType((*Pair)(nil), "proto.Pair")
	proto.RegisterType((*GetAllDataRequest)(nil), "proto.GetAllDataRequest")
	proto.RegisterType((*GetAllDataResponse)(nil), "proto.GetAllDataResponse")
	proto.RegisterType((*DeleteDataRequest)(nil), "proto.DeleteDataRequest")
	proto.RegisterType((*DeleteDataResponse)(nil), "proto.DeleteDataResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Server service

type ServerClient interface {
	GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error)
	SetData(ctx context.Context, in *SetDataRequest, opts ...grpc.CallOption) (*SetDataResponse, error)
	GetAllData(ctx context.Context, in *GetAllDataRequest, opts ...grpc.CallOption) (*GetAllDataResponse, error)
	DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) GetData(ctx context.Context, in *GetDataRequest, opts ...grpc.CallOption) (*GetDataResponse, error) {
	out := new(GetDataResponse)
	err := grpc.Invoke(ctx, "/proto.Server/GetData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) SetData(ctx context.Context, in *SetDataRequest, opts ...grpc.CallOption) (*SetDataResponse, error) {
	out := new(SetDataResponse)
	err := grpc.Invoke(ctx, "/proto.Server/SetData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) GetAllData(ctx context.Context, in *GetAllDataRequest, opts ...grpc.CallOption) (*GetAllDataResponse, error) {
	out := new(GetAllDataResponse)
	err := grpc.Invoke(ctx, "/proto.Server/GetAllData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) DeleteData(ctx context.Context, in *DeleteDataRequest, opts ...grpc.CallOption) (*DeleteDataResponse, error) {
	out := new(DeleteDataResponse)
	err := grpc.Invoke(ctx, "/proto.Server/DeleteData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Server service

type ServerServer interface {
	GetData(context.Context, *GetDataRequest) (*GetDataResponse, error)
	SetData(context.Context, *SetDataRequest) (*SetDataResponse, error)
	GetAllData(context.Context, *GetAllDataRequest) (*GetAllDataResponse, error)
	DeleteData(context.Context, *DeleteDataRequest) (*DeleteDataResponse, error)
}

func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_GetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).GetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Server/GetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).GetData(ctx, req.(*GetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_SetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).SetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Server/SetData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).SetData(ctx, req.(*SetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_GetAllData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).GetAllData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Server/GetAllData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).GetAllData(ctx, req.(*GetAllDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_DeleteData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).DeleteData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Server/DeleteData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).DeleteData(ctx, req.(*DeleteDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetData",
			Handler:    _Server_GetData_Handler,
		},
		{
			MethodName: "SetData",
			Handler:    _Server_SetData_Handler,
		},
		{
			MethodName: "GetAllData",
			Handler:    _Server_GetAllData_Handler,
		},
		{
			MethodName: "DeleteData",
			Handler:    _Server_DeleteData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_server_e535c14c20fe8460) }

var fileDescriptor_server_e535c14c20fe8460 = []byte{
	// 339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0x02, 0x41,
	0x18, 0xc6, 0x59, 0x4d, 0xad, 0xd7, 0xf0, 0xcf, 0xab, 0x89, 0x4a, 0x07, 0x99, 0x88, 0xc4, 0x83,
	0x0b, 0x76, 0xa9, 0x6e, 0x81, 0xe0, 0x55, 0x9c, 0x53, 0xc7, 0x09, 0x5e, 0x44, 0x1c, 0x76, 0x6c,
	0x66, 0x14, 0x24, 0xba, 0xf4, 0x15, 0xfa, 0x68, 0x7d, 0x80, 0x2e, 0x7d, 0x90, 0x70, 0x77, 0x74,
	0xd7, 0x55, 0xaa, 0xd3, 0xee, 0xce, 0x3c, 0xef, 0xef, 0x79, 0xf9, 0x2d, 0x9c, 0x1b, 0xd2, 0x2b,
	0xd2, 0xfd, 0x85, 0x56, 0x56, 0x61, 0x2e, 0x7c, 0xb4, 0x2f, 0xa7, 0x4a, 0x4d, 0x25, 0xf9, 0x62,
	0x31, 0xf3, 0x45, 0x10, 0x28, 0x2b, 0xec, 0x4c, 0x05, 0x26, 0x0a, 0x31, 0x06, 0xa5, 0x11, 0xd9,
	0xa1, 0xb0, 0x62, 0x42, 0x2f, 0x4b, 0x32, 0x16, 0x2b, 0x90, 0x9d, 0xd3, 0xba, 0xe9, 0x75, 0xbc,
	0xee, 0xd9, 0x64, 0xf3, 0xca, 0x6e, 0xa0, 0xbc, 0xcb, 0x98, 0x85, 0x0a, 0x0c, 0x61, 0x1d, 0x72,
	0x2b, 0x21, 0x97, 0xe4, 0x62, 0xd1, 0x07, 0xbb, 0x83, 0x12, 0xff, 0x03, 0x16, 0x4f, 0x66, 0x92,
	0x93, 0x55, 0x28, 0xf3, 0xfd, 0x0a, 0xd6, 0x87, 0x93, 0xb1, 0x98, 0xe9, 0x7f, 0x23, 0x6a, 0x50,
	0x1d, 0x91, 0x7d, 0x94, 0x32, 0xd1, 0xcf, 0xee, 0x01, 0x93, 0x87, 0x6e, 0xfb, 0x2b, 0xc8, 0x6b,
	0x32, 0x4b, 0x69, 0x9b, 0x5e, 0x27, 0xdb, 0x2d, 0x0e, 0x8a, 0x91, 0x8c, 0xfe, 0xa6, 0x6f, 0xe2,
	0xae, 0xd8, 0x35, 0x54, 0x87, 0x24, 0xc9, 0xd2, 0xef, 0x72, 0xea, 0x80, 0xc9, 0x58, 0xd4, 0x30,
	0xf8, 0xca, 0x40, 0x9e, 0x87, 0x3f, 0x03, 0xc7, 0x50, 0x70, 0xf6, 0xf0, 0xc2, 0xf5, 0xec, 0x1b,
	0x6f, 0x37, 0xd2, 0xc7, 0xce, 0x40, 0xe3, 0xfd, 0xf3, 0xfb, 0x23, 0x53, 0xc1, 0x92, 0x3f, 0x5f,
	0x19, 0xab, 0x34, 0xf9, 0xaf, 0x73, 0x5a, 0xbf, 0x21, 0x87, 0x02, 0x4f, 0x11, 0xf9, 0x71, 0x62,
	0xda, 0x69, 0x2b, 0x24, 0xd6, 0x58, 0x8a, 0xf8, 0xe0, 0xf5, 0x90, 0x03, 0xc4, 0xa6, 0xb0, 0x19,
	0xaf, 0xb4, 0x6f, 0xb4, 0xdd, 0x3a, 0x72, 0xe3, 0xe8, 0x95, 0x90, 0x0e, 0x78, 0xba, 0xa5, 0xe3,
	0x13, 0x40, 0x2c, 0x67, 0x07, 0x3d, 0xd0, 0xba, 0x83, 0x1e, 0x9a, 0xdc, 0x4a, 0xe8, 0xa5, 0x56,
	0x7e, 0xce, 0x87, 0x13, 0xb7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x73, 0x72, 0xa1, 0x3b, 0xf4,
	0x02, 0x00, 0x00,
}
